version: '3.5'

services:
  postgres:
    image: postgres:12.2
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    expose:
      - 5432
    ports:
      - "7000:5432"
    restart: unless-stopped

  init-db:
    build: scripts/
    links:
      - postgres
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASS: changeme

#  pgadmin:
#    image: dpage/pgadmin4:4.19
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#    volumes:
#      - pgadmin:/root/.pgadmin
#    ports:
#      - "${PGADMIN_PORT:-5051}:80"
#    networks:
#      - postgres
#    restart: unless-stopped

volumes:
  postgres:
  pgadmin: