package org.technbolts.busd.core;

public enum Permission {
    TENANT_CREATE,
    TENANT_READ,
    TENANT_UPDATE,
    AUDIT_META_READ,
    AUTHORITY_CREATE,
    AUTHORITY_UPDATE,
    AUTHORITY_READ,
    OPERATOR_CREATE,
    OPERATOR_READ,
    OPERATOR_UPDATE,
    TRANSPORT_MODE_CREATE,
    TRANSPORT_MODE_READ,
    TRANSPORT_MODE_UPDATE,
    VEHICLE_CREATE,
    VEHICLE_READ,
    VEHICLE_UPDATE,
}
